// BFF/v4/MultiFrontend/frontends/customer-portal/src/App.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import HelloWorld from './components/HelloWorld.vue'

const user = ref<any[] | null>(null)
const loading = ref(true)

const getClaim = (type: string) => {
  if (!user.value) return null
  const claim = user.value.find((c: any) => c.type === type)
  return claim ? claim.value : null
}

onMounted(async () => {
  try {
    const res = await fetch('/bff/user', { credentials: 'include' })
    if (!res.ok) {
      user.value = null
    } else {
      const claims = await res.json()
      if (Array.isArray(claims) && claims.length > 0) {
        user.value = claims
      } else {
        user.value = null
      }
    }
  } catch {
    user.value = null
  }
  loading.value = false
})
</script>

<template>
  <div>
    <a href="https://vite.dev" target="_blank">
      <img src="/vite.svg" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
  </div>
  <HelloWorld msg="Vite + Vue" />

  <div style="margin-top:2rem">
    <template v-if="loading">
      Loading...
    </template>
    <template v-else>
      <template v-if="!user">
        <button @click="window.location.href = '/bff/login'">Login</button>
      </template>
      <template v-else>
        <button @click="window.location.href = getClaim('bff:logout_url') || '/bff/logout'">Logout</button>
        <div style="margin-top:1rem;text-align:left">
          <h3>User Info</h3>
          <ul>
            <li><strong>Name:</strong> {{ getClaim('name') }}</li>
            <li><strong>Subject:</strong> {{ getClaim('sub') }}</li>
            <li><strong>IdP:</strong> {{ getClaim('idp') }}</li>
            <li><strong>SID:</strong> {{ getClaim('sid') }}</li>
            <li><strong>Logout URL:</strong> {{ getClaim('bff:logout_url') }}</li>
          </ul>
        </div>
      </template>
    </template>
  </div>
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>

// BFF/v4/MultiFrontend/frontends/management-app/src/App.tsx
import { useState, useEffect } from 'react'
import reactLogo from './assets/react.svg'
import viteLogo from '/vite.svg'
import './App.css'

interface Claim{
  type: string;
  value: string;
}

function App() {
  const [count, setCount] = useState(0)
  const [user, setUser] = useState<Claim[]>([]);
  const [loading, setLoading] = useState(true);

  // Fetch user info on mount
  useEffect(() => {
    fetch('/management/bff/user', { credentials: 'include' })
      .then(async (res) => {
        if (!res.ok) {
          setUser([]);
        } else {
          const claims = await res.json();
          if (Array.isArray(claims) && claims.length > 0) {
            setUser(claims);
          } else {
            setUser([]);
          }
        }
        setLoading(false);
      })
      .catch(() => {
        setUser([]);
        setLoading(false);
      });
  }, []);

  // Helper to get claim value by type
  const getClaim = (type: string) => {
    if (!user) return null;
    const claim = user.find((c: any) => c.type === type);
    return claim ? claim.value : null;
  };

  if (loading) {
    return <div>Loading...</div>;
  }

  return (
    <>
      <div>
        <a href="https://vite.dev" target="_blank">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Vite + React</h1>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>
        <p>
          Edit <code>src/App.tsx</code> and save to test HMR
        </p>
      </div>
      {/* Login/Logout UI */}
      <div style={{ marginTop: '2rem' }}>
          {!user.length ? (
            <button onClick={() => window.location.href = '/management/bff/login'}>
              Login
            </button>
          ) : (
            <>
              <button onClick={() => window.location.href = getClaim('bff:logout_url') || '/management/bff/logout'}>
                Logout
              </button>
              <div style={{ marginTop: '1rem', textAlign: 'left' }}>
                <h3>User Info</h3>
                <ul>
                  <li><strong>Name:</strong> {getClaim('name')}</li>
                  <li><strong>Subject:</strong> {getClaim('sub')}</li>
                  <li><strong>IdP:</strong> {getClaim('idp')}</li>
                  <li><strong>SID:</strong> {getClaim('sid')}</li>
                  <li><strong>Logout URL:</strong> {getClaim('bff:logout_url')}</li>
                </ul>
              </div>
            </>
          )}
      </div>
      <p className="read-the-docs">
        Click on the Vite and React logos to learn more
      </p>
    </>
  )
}

export default App
