// IdentityServer/v7/BFF/React/react.client/src/components/NavMenu.jsx
import React, { Component } from "react";
import { Link } from "react-router-dom";
import {
  Collapse,
  Container,
  Navbar,
  NavbarBrand,
  NavbarToggler,
  NavItem,
  NavLink,
} from "reactstrap";
import "./NavMenu.css";

export class NavMenu extends Component {
  static displayName = NavMenu.name;

  constructor(props) {
    super(props);

    this.toggleNavbar = this.toggleNavbar.bind(this);
    this.state = {
      collapsed: true,
      loggedIn: false,
      logoutUrl: "/bff/logout",
    };

    this.fetchIsUserLoggedIn = this.fetchIsUserLoggedIn.bind(this);
  }

  componentDidMount() {
    (async () => this.fetchIsUserLoggedIn())();
  }

  toggleNavbar() {
    this.setState({
      collapsed: !this.state.collapsed,
    });
  }

  async fetchIsUserLoggedIn() {
    try {
      const response = await fetch("/bff/user", {
        headers: {
          "X-CSRF": 1,
        },
      });

      if (response.ok && response.status === 200) {
        const data = await response.json();
        const logoutUrl =
          data.find((claim) => claim.type === "bff:logout_url")?.value ??
          this.state.logoutUrl;
        this.setState({ loggedIn: true, logoutUrl });
      }
    } catch (e) {
      console.error(e);
      this.setState({ loggedIn: false });
    }
  }

  render() {
    return (
      <header>
        <Navbar
          className="navbar-expand-sm navbar-toggleable-sm ng-white border-bottom box-shadow mb-3"
          light
        >
          <Container>
            <NavbarBrand tag={Link} to="/">
              React Bff Sample
            </NavbarBrand>
            <NavbarToggler onClick={this.toggleNavbar} className="mr-2" />
            <Collapse
              className="d-sm-inline-flex flex-sm-row-reverse"
              isOpen={!this.state.collapsed}
              navbar
            >
              <ul className="navbar-nav flex-grow">
                <NavItem>
                  <NavLink tag={Link} className="text-dark" to="/">
                    Home
                  </NavLink>
                </NavItem>
                {this.state.loggedIn && (
                  <NavItem>
                    <NavLink
                      tag={Link}
                      className="text-dark"
                      to="/user-session"
                    >
                      Show User Session
                    </NavLink>
                  </NavItem>
                )}
                <NavItem>
                  <a
                    className="text-dark nav-link"
                    href={
                      this.state.loggedIn ? this.state.logoutUrl : "/bff/login"
                    }
                  >
                    {this.state.loggedIn ? "Logout" : "Login"}
                  </a>
                </NavItem>
              </ul>
            </Collapse>
          </Container>
        </Navbar>
      </header>
    );
  }
}

// IdentityServer/v6/BFF/AngularBffSample/src/FrontendHost/ClientApp/src/app/nav-menu/nav-menu.component.ts
import { Component } from '@angular/core';
import { AuthenticationService } from '../authentication.service';

@Component({
  selector: 'app-nav-menu',
  templateUrl: './nav-menu.component.html',
  styleUrls: ['./nav-menu.component.css']
})
export class NavMenuComponent {
  public username$ = this.auth.username$;
  public authenticated$ = this.auth.authenticated$;
  public anonymous$ = this.auth.anonymous$;

  constructor(private auth: AuthenticationService) {
    auth.getSession();
  }

  isExpanded = false;

  collapse() {
    this.isExpanded = false;
  }

  toggle() {
    this.isExpanded = !this.isExpanded;
  }
}

<header>
  <nav
    class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3"
  >
    <div class="container">
      <a class="navbar-brand" [routerLink]="['/']">Angular BFF Sample</a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target=".navbar-collapse"
        aria-label="Toggle navigation"
        [attr.aria-expanded]="isExpanded"
        (click)="toggle()"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div
        class="navbar-collapse collapse d-sm-inline-flex justify-content-end"
        [ngClass]="{ show: isExpanded }"
      >
        <ul class="navbar-nav flex-grow">
          <li class="nav-item"
              [routerLinkActive]="['link-active']"
              [routerLinkActiveOptions]="{ exact: true }">
            <a class="nav-link text-dark" [routerLink]="['/']">Home</a>
          </li>

          <li *ngIf="authenticated$ | async" class="nav-item"
              [routerLinkActive]="['link-active']"
              [routerLinkActiveOptions]="{ exact: true }">
            <a class="nav-link text-dark" [routerLink]="['/user-session']">Show User Session</a>
          </li>

          <li *ngIf="anonymous$ | async" class="nav-item">
            <a class="nav-link text-dark" href="/bff/login">Login</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>
